
package my.learn.wsimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MathService", targetNamespace = "http://webservice.learn.my/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MathService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "add", targetNamespace = "http://webservice.learn.my/", className = "my.learn.wsimport.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://webservice.learn.my/", className = "my.learn.wsimport.AddResponse")
    @Action(input = "http://webservice.learn.my/MathService/addRequest", output = "http://webservice.learn.my/MathService/addResponse")
    public int add(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "hello", targetNamespace = "http://webservice.learn.my/", className = "my.learn.wsimport.Hello")
    @ResponseWrapper(localName = "helloResponse", targetNamespace = "http://webservice.learn.my/", className = "my.learn.wsimport.HelloResponse")
    @Action(input = "http://webservice.learn.my/MathService/helloRequest", output = "http://webservice.learn.my/MathService/helloResponse")
    public String hello(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
